#ifndef MENU_DESFS_INCLUDED
#define MENU_DEFS_INCLUDED

#define MENU_OPEN_FILE 101
#define MENU_EXIT 102
#define MENU_RAW_MODE 201
#define MENU_LAYOUT_MODE 202
#define MENU_HELP 301

#endif /* MENU_DEFS_INCLUDED */